import 'package:dental_proj/Widgets/teeth_widget.dart';
import 'package:flutter/material.dart';

class TeethDownDataWidget extends StatelessWidget {
  const TeethDownDataWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return const Stack(
      children: [
        TeethWidget(
          topP: 360,
          liftP: 325,
          heightImg: 45,
          teethName: 38,
          toothId: 38,
          teethNumber: 17,
          teethimg: 'images/17-lastest.png',
        ),
        TeethWidget(
          topP: 404,
          liftP: 325,
          heightImg: 45,
          teethName: 37,
          toothId: 37,
          teethNumber: 18,
          teethimg: 'images/18-lastest.png',
        ),
        TeethWidget(
          topP: 445,
          liftP: 320,
          heightImg: 45,
          teethName: 36,
          toothId: 36,
          teethNumber: 19,
          teethimg: 'images/19-lastest.png',
        ),
        TeethWidget(
          topP: 485,
          liftP: 310,
          heightImg: 45,
          teethName: 35,
          toothId: 35,
          teethNumber: 20,
          teethimg: 'images/20-lastest.png',
        ),
        TeethWidget(
          topP: 522,
          liftP: 291,
          heightImg: 45,
          teethName: 34,
          toothId: 34,
          teethNumber: 21,
          teethimg: 'images/21-lastest.png',
        ),
        TeethWidget(
          topP: 550,
          liftP: 267,
          heightImg: 45,
          teethName: 33,
          toothId: 33,
          teethNumber: 22,
          teethimg: 'images/22-lastest.png',
        ),
        TeethWidget(
          topP: 575,
          liftP: 240,
          heightImg: 45,
          teethName: 32,
          toothId: 32,
          teethNumber: 23,
          teethimg: 'images/23-lastest.png',
        ),
        TeethWidget(
          topP: 590,
          liftP: 200,
          heightImg: 45,
          teethName: 31,
          toothId: 31,
          teethNumber: 24,
          teethimg: 'images/24-lastest.png',
        ),
        TeethWidget(
          topP: 590,
          liftP: 155,
          heightImg: 45,
          teethName: 41,
          toothId: 41,
          teethNumber: 25,
          teethimg: 'images/25-lastest.png',
        ),
        TeethWidget(
          topP: 575,
          liftP: 115,
          heightImg: 45,
          teethName: 42,
          toothId: 42,
          teethNumber: 26,
          teethimg: 'images/26-lastest.png',
        ),
        TeethWidget(
          topP: 545,
          liftP: 95,
          heightImg: 45,
          teethName: 43,
          toothId: 43,
          teethNumber: 27,
          teethimg: 'images/27-lastest.png',
        ),
        TeethWidget(
          topP: 512,
          liftP: 75,
          heightImg: 45,
          teethName: 44,
          toothId: 44,
          teethNumber: 28,
          teethimg: 'images/28-lastest.png',
        ),
        TeethWidget(
          topP: 472,
          liftP: 55,
          heightImg: 45,
          teethName: 45,
          toothId: 45,
          teethNumber: 29,
          teethimg: 'images/29-lastest.png',
        ),
        TeethWidget(
          topP: 435,
          liftP: 40,
          heightImg: 45,
          teethName: 46,
          toothId: 46,
          teethNumber: 30,
          teethimg: 'images/30-lastest.png',
        ),
        TeethWidget(
          topP: 396,
          liftP: 35,
          heightImg: 45,
          teethName: 47,
          toothId: 47,
          teethNumber: 31,
          teethimg: 'images/31-lastest.png',
        ),
        TeethWidget(
          topP: 356,
          liftP: 40,
          heightImg: 42,
          teethName: 48,
          toothId: 48,
          teethNumber: 32,
          teethimg: 'images/32-lastest.png',
        ),
      ],
    );
  }
}
